# download serial == 0 from https://wandb.ai/nycu_pcs/FGIRFT/ into fgirft_stage1.csv
# wandb make scripts for stage 2 (seed) from stage 1 (lr)
python download_save_wandb_data.py  --output_file fgirft_stage1_lr.csv

# accuracy
python summarize_acc.py

# cost not all have the same datasets so in order to get the average need to select a subset
# default uses the subset from ufgir
python summarize_cost.py

hivit_base_patch16_224.orig_in21k hivit_base_patch16_224_miil.in21k hideit_base_patch16_224.fb_in1k hideit3_base_patch16_224.fb_in1k hideit3_base_patch16_224.fb_in22k_ft_in1k hivit_base_patch16_clip_224.laion2b hivit_base_patch16_224.mae hivit_base_patch16_224.in1k_mocov3 hivit_base_patch16_224.dino
hiresnet50.tv_in1k hiresnet50.tv2_in1k hiresnet50.gluon_in1k hiresnet50.fb_swsl_ig1b_ft_in1k hiresnet50.fb_ssl_yfcc100m_ft_in1k hiresnet50.a1_in1k

python plot.py --title "Max Accuracy FSL Resnets(Aircraft)" --keep_serials 23 --output_file max_resnet_fsl_acc(aircraft) --y_lim 90 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_fsl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy FSL Resnets(Aircraft) fz" --keep_serials 24 --output_file max_resnet_fsl_acc(aircraft)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_fsl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy SSL Resnets(Aircraft)" --keep_serials 23 --output_file max_resnet_ssl_acc(aircraft) --y_lim 85 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_ssl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy SSL Resnets(Aircraft) fz" --keep_serials 24 --output_file max_resnet_ssl_acc(aircraft)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_ssl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy FSL Resnets(CUB)" --keep_serials 23 --output_file max_resnet_fsl_acc(cub) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_fsl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy FSL Resnets(CUB) fz" --keep_serials 24 --output_file max_resnet_fsl_acc(cub)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_fsl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy SSL Resnets(CUB)" --keep_serials 23 --output_file max_resnet_ssl_acc(cub) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_ssl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy SSL Resnets(CUB) fz" --keep_serials 24 --output_file max_resnet_ssl_acc(cub)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_ssl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy FSL Resnets(Cars)" --keep_serials 23 --output_file max_resnet_fsl_acc(cars) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_fsl --keep_datasets cars --summarized
python plot.py --title "Max Accuracy FSL Resnets(Cars) fz" --keep_serials 24 --output_file max_resnet_fsl_acc(cars)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_fsl --keep_datasets cars --summarized
python plot.py --title "Max Accuracy SSL Resnets(Cars)" --keep_serials 23 --output_file max_resnet_ssl_acc(cars) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_ssl --keep_datasets cars --summarized
python plot.py --title "Max Accuracy SSL Resnets(Cars) fz" --keep_serials 24 --output_file max_resnet_ssl_acc(cars)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family resnet_ssl --keep_datasets cars --summarized

python plot.py --title "Max Accuracy FSL ViTs(Aircraft)" --keep_serials 23 --output_file max_vit_fsl_acc(aircraft) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_fsl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy FSL ViTs(Aircraft) fz" --keep_serials 24 --output_file max_vit_fsl_acc(aircraft)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_fsl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy SSL ViTs(Aircraft)" --keep_serials 23 --output_file max_vit_ssl_acc(aircraft) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_ssl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy SSL ViTs(Aircraft) fz" --keep_serials 24 --output_file max_vit_ssl_acc(aircraft)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_ssl --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy FSL ViTs(CUB)" --keep_serials 23 --output_file max_vit_fsl_acc(cub) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_fsl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy FSL ViTs(CUB) fz" --keep_serials 24 --output_file max_vit_fsl_acc(cub)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_fsl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy SSL ViTs(CUB)" --keep_serials 23 --output_file max_vit_ssl_acc(cub) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_ssl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy SSL ViTs(CUB) fz" --keep_serials 24 --output_file max_vit_ssl_acc(cub)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_ssl --keep_datasets cub --summarized
python plot.py --title "Max Accuracy FSL ViTs(Cars)" --keep_serials 23 --output_file max_vit_fsl_acc(cars) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_fsl --keep_datasets cars --summarized
python plot.py --title "Max Accuracy FSL ViTs(Cars) fz" --keep_serials 24 --output_file max_vit_fsl_acc(cars)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_fsl --keep_datasets cars --summarized
python plot.py --title "Max Accuracy SSL ViTs(Cars)" --keep_serials 23 --output_file max_vit_ssl_acc(cars) --y_lim 80 100 --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_ssl --keep_datasets cars --summarized
python plot.py --title "Max Accuracy SSL ViTs(Cars) fz" --keep_serials 24 --output_file max_vit_ssl_acc(cars)fz --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --method_family vit_ssl --keep_datasets cars --summarized

python plot.py --title "Learning Rate on FSL Resnet(Aircraft)" --keep_serials 23 --output_file lr_resnet_fsl(aircraft) --y_lim 85 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --method_family resnet_fsl --keep_datasets aircraft 
python plot.py --title "Learning Rate on FSL Resnet(Aircraft)fz" --keep_serials 24 --output_file lr_resnet_fsl(aircraft)fz --y_lim 20 75 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --method_family resnet_fsl --keep_datasets aircraft 
python plot.py --title "Learning Rate on SSL Resnet(Aircraft)" --keep_serials 23 --output_file lr_resnet_ssl(aircraft) --y_lim 85 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --method_family resnet_ssl --keep_datasets aircraft 
python plot.py --title "Learning Rate on SSL Resnet(Aircraft)fz" --keep_serials 24 --output_file lr_resnet_ssl(aircraft)fz --y_lim 0 75 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --method_family resnet_ssl --keep_datasets aircraft 

python plot.py --title "Learning Rate on FSL Resnet(Aircraft)" --keep_serials 23 --output_file lr_resnet_fsl(aircraft) --type_plot reg --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --method_family resnet_fsl --keep_datasets aircraft 

python plot.py --title "Learning Rate on Resnet(CUB)" --output_file lr_resnet(cub) --y_lim 60 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --keep_datasets cub 
python plot.py --title "Standard Deviation ViT(Aircraft)" --output_file std_vit(aircraft) --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets aircraft --summarized
python plot.py --title "Standard Deviation ViT(CUB)" --output_file std_vit(cub) --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets cub --summarized
#python plot.py --title "Max Accuracy Resnets(CUB)" --output_file max_resnet_acc(cub) --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets cub --summarized
python plot.py --title "Max Accuracy ViTs(Aircraft)" --output_file max_vit_acc(aircraft) --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets aircraft --summarized
python plot.py --title "Max Accuracy ViT(CUB)"--output_file max_vit_acc(cub) --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets cub --summarized
python plot.py --title "Max Accuracy All" -output_file max_acc_all --y_label Accuracy(%) --y_var_name acc_max --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_dataset aircraft cub --summarized
python plot.py --title "Overall Accuracy Resnets(Aircraft)" --output_file ov_max_acc_resnet(aircraft) --y_label Accuracy(%) --y_var_name acc --x_var_name method --type_plot box --input_file data\hierarchical_test.csv --keep_datasets aircraft
python plot.py --title "Overall Accuracy Resnets(CUB)" --output_file ov_max_acc_resnet(cub) --y_label Accuracy(%) --y_var_name acc --x_var_name method --type_plot box --input_file data\hierarchical_test.csv --keep_datasets cub
python plot.py --title "Overall Accuracy ViTs(Aircraft)" --output_file ov_max_acc_vit(aircraft) --y_label Accuracy(%) --y_var_name acc --x_var_name method --type_plot box --input_file data\hierarchical_test.csv --keep_datasets aircraft
python plot.py --title "Overall Accuracy ViTs(CUB)" --output_file ov_max_acc_vit(cub) --y_label Accuracy(%) --y_var_name acc --x_var_name method --type_plot box --input_file data\hierarchical_test.csv --keep_datasets cub
python plot.py --title "Overall Accuracy All" --output_file ov_max_acc --y_label Accuracy(%) --y_var_name acc --x_var_name method --type_plot box --input_file data\hierarchical_test.csv --keep_datasets aircraft cub
python plot.py --title "Learning Rate on Resnet(Aircraft)" --output_file lr_resnet(aircraft) --y_lim 85 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --keep_datasets aircraft 
python plot.py --title "Learning Rate on Resnet(CUB)" --output_file lr_resnet(cub) --y_lim 60 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --keep_datasets cub 
python plot.py --title "Learning Rate on ViT(Aircraft)" --output_file lr_vit(aircraft) --loc_legend "upper left" --y_lim 60 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --keep_datasets aircraft
python plot.py --title "Learning Rate on ViT(CUB)" --output_file lr_vit(cub) --loc_legend "upper center" --y_lim 40 100 --x_label "Learning Rate" --y_label Accuracy(%) --hue_var_name method --y_var_name acc --x_var_name lr --input_file data\hierarchical_test.csv --keep_datasets cub 
python plot.py --title "Standard Deviation Resnet(Aircraft)" --output_file std_resnet(aircraft) --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets aircraft --summarized 
python plot.py --title "Standard Deviation Resnet(CUB)" --output_file std_resnet(cub) --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets cub --summarized
python plot.py --title "Standard Deviation ViT(Aircraft)" --output_file std_vit(aircraft) --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets aircraft --summarized
python plot.py --title "Standard Deviation ViT(CUB)" --output_file std_vit(cub) --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets cub --summarized
python plot.py --title "Standard Deviation All" --output_file std_all --y_label Standard Deviation --y_var_name acc_std --x_var_name method --input_file results_all\acc\summarized_acc_hierarchical_main.csv --keep_datasets aircraft cub --summarized
python plot.py --title "Resnet Throughput" --output_file throughput_resnet --y_label Throughput --y_var_name tp_train --x_var_name method --input_file results_all\cost\cost_hierarchical.csv --summarized
python plot.py --title "ViT Throughput" --output_file throughput_vit --y_label Throughput --y_var_name tp_train --x_var_name method --input_file results_all\cost\cost_hierarchical.csv --summarized


python plot.py --output_file test --y_var_name acc --input_file data\hierarchical_test.csv
python plot.py --output_file test --y_var_name acc --input_file data\hierarchical_test.csv --fig_size 12 6 