#!/bin/bash

# Missing batch_size
# python download_save_wandb_data.py --serials 64 65 --output_file hierarchical_epochs.csv
# python summarize_acc.py --input_file data/hierarchical_epochs.csv --main_serials 64 65 --results_dir results_all/acc/acc_epochs
# python organize_pseudo.py --input_csv results_all/acc/acc_epochs/summary_val_acc_level1_main.csv --main_serials 64 65 --output_dir pseudo_results/epochs

# python download_save_wandb_data.py --serials 66 67 --output_file hierarchical_is.csv
# python summarize_acc.py --input_file data/hierarchical_is.csv --main_serials 66 67 --results_dir results_all/acc/acc_is
# python organize_pseudo.py --input_csv results_all/acc/acc_is/summary_val_acc_level1_main.csv --main_serials 66 67 --output_dir pseudo_results/image_size

# python download_save_wandb_data.py --serials 68 69 --output_file hierarchical_augs.csv
# python summarize_acc.py --input_file data/hierarchical_augs.csv --main_serials 68 69 --results_dir results_all/acc/acc_augs
# python organize_pseudo.py --input_csv results_all/acc/acc_augs/summary_val_acc_level1_main.csv --main_serials 68 69 --output_dir pseudo_results/augs

# python download_save_wandb_data.py --serials 70 --output_file hierarchical_model_size.csv
# python summarize_acc.py --input_file data/hierarchical_model_size.csv --main_serials 70 --results_dir results_all/acc/acc_model_size
# python organize_pseudo.py --input_csv results_all/acc/acc_model_size/summary_val_acc_level1_main.csv --main_serials 70 --output_dir pseudo_results/model_size

# python download_save_wandb_data.py --serials 40 52 53 --output_file hierarchical_algo.csv
# python summarize_acc.py --input_file data/hierarchical_algo.csv --main_serials 40 52 53 --results_dir results_all/acc/acc_algo
# python organize_pseudo.py --input_csv results_all/acc/acc_algo/summary_val_acc_level1_main.csv --main_serials 40 52 53 --output_dir pseudo_results/clus_algo

# python download_save_wandb_data.py --serials 40 51 --output_file hierarchical_diff_extractor.csv
# python summarize_acc.py --input_file data/hierarchical_diff_extractor.csv --main_serials 40 51 --results_dir results_all/acc/acc_extractor
# python organize_pseudo.py --input_csv results_all/acc/acc_extractor/summary_val_acc_level1_main.csv --main_serials 40 51 --output_dir pseudo_results/diff_extractor

# python download_save_wandb_data.py --serials 54 55 --output_file hierarchical_soylocal.csv
# python summarize_acc.py --input_file data/hierarchical_soylocal.csv --main_serials 54 55 --results_dir results_all/acc/acc_soylocal
# python organize_pseudo.py --input_csv results_all/acc/acc_soylocal/summary_val_acc_level1_main.csv --main_serials 54 55 --output_dir pseudo_results/soylocal

# python download_save_wandb_data.py --serials 40 23 32 --output_file hierarchical_pseudo_2.csv
# python summarize_acc.py --input_file data/hierarchical_pseudo_2.csv --main_serials 40 23 32 --results_dir results_all/acc/acc_pseudo_main
# python organize_pseudo.py --input_csv results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --main_serials 32 23 40 --output_dir pseudo_results/main_results

all_resnet=('hiresnet50.tv_in1k' 'hiresnet50.tv2_in1k' 'hiresnet50.gluon_in1k' 'hiresnet50.fb_swsl_ig1b_ft_in1k' 'hiresnet50.fb_ssl_yfcc100m_ft_in1k' 'hiresnet50.a1_in1k' 'hiresnet50.in1k_mocov3' 'hiresnet50.in1k_spark' 'hiresnet50.in1k_supcon' 'hiresnet50.in1k_swav' 'hiresnet50.in21k_miil')
all_vit=('hivit_base_patch16_224.orig_in21k' 'hivit_base_patch16_224_miil.in21k' 'hideit_base_patch16_224.fb_in1k' 'hideit3_base_patch16_224.fb_in1k' 'hideit3_base_patch16_224.fb_in22k_ft_in1k' 'hivit_base_patch16_clip_224.laion2b' 'hivit_base_patch16_224.mae' 'hivit_base_patch16_224.in1k_mocov3' 'hivit_base_patch16_224.dino' 'hivit_base_patch16_siglip_224.v2_webli')
all_models=("${all_resnet[@]}" "${all_vit[@]}")

# python -u plot.py --keep_serials 68 69 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/hierarchical_augs.csv --output_file compare_augs --title 'Comparison of 12 augmentations of Aircraft with hideit3_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
# python -u plot.py --keep_serials 66 67 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/hierarchical_is.csv --output_file compare_is --title 'Comparison of 10 image sizes (is) of Aircraft with hideit3_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
# python -u plot.py --keep_serials 64 65 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/hierarchical_epochs.csv --output_file compare_epochs --title 'Comparison of 10 epochs of Aircraft with hideit3_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
# python -u plot.py --keep_serials 70 --x_var_name model_name_extractor --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/hierarchical_model_size.csv --output_file compare_model_size --title 'Comparison of hideit3_base_patch16_224.fb_in1k model sizes on Aircraft in Baseline vs Pseudo-Hierarchy settings'
# python -u plot.py --keep_serials 70 --summarized --x_var_name model_name_extractor --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --type_plot bar --input_file results_all/acc/acc_model_size/summary_val_acc_level1_main.csv --output_file compare_model_size_ada --title 'Comparison of hideit3_base_patch16_224.fb_in1k model sizes on Aircraft in Baseline vs Pseudo-Hierarchy settings'

# python -u plot.py --keep_serials 40 52 --x_ticks_labels 'HPH' 'Kmean' --font_scale 1.75 --fig_size 8 6 --keep_ratios 50 --keep_dataset aircraft_pl --keep_methods hideit3_base_patch16_224.fb_in1k --x_var_name serial --y_label 'Accuracy (%)' --y_var_name val_acc_level1 --type_plot box --input_file data/hierarchical_algo.csv --output_file compare_algo_all --title 'Clustering algorithms on Aircraft with hideit3_base_patch16_224.fb_in1k'
# python -u plot.py --keep_serials 40 52 --keep_ratios 50 --keep_dataset aircraft_pl --keep_methods hideit3_base_patch16_224.fb_in1k --x_var_name serial --y_label 'Accuracy (%)' --y_var_name val_acc_level1 --type_plot box --input_file data/hierarchical_algo.csv --output_file compare_algo_only_kmeans --title 'Comparison of different clustering algorithm on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --keep_dataset aircraft_pl --keep_methods hideit3_base_patch16_224.fb_in1k --keep_extractor ${all_resnet[@]} --x_var_name model_name_extractor --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/hierarchical_diff_extractor.csv --output_file compare_extractors_rn --title 'Overall performance of different Resnet extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --keep_dataset aircraft_pl --keep_methods hideit3_base_patch16_224.fb_in1k --keep_extractor ${all_vit[@]} --x_var_name model_name_extractor --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/hierarchical_diff_extractor.csv --output_file compare_extractors_vit --title 'Overall performance of ViT extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --summarized --keep_methods hideit3_base_patch16_224.fb_in1k --keep_dataset aircraft_pl --x_var_name model_name_extractor --y_var_name acc_std --y_label 'Accuracy Standard Deviation' --keep_extractor ${all_vit[@]} --x_var_name model_name_extractor --type_plot bar --input_file results_all/acc/acc_extractor/summary_val_acc_level1_main.csv --output_file compare_extractors_std_vit --title 'StD performance of ViT extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --summarized --keep_methods hideit3_base_patch16_224.fb_in1k --keep_dataset aircraft_pl --x_var_name model_name_extractor --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --keep_extractor ${all_vit[@]} --x_var_name model_name_extractor --type_plot bar --input_file results_all/acc/acc_extractor/summary_val_acc_level1_main.csv --output_file compare_extractors_ada_vit --title 'ADA ratio of ViT extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --summarized --keep_methods hideit3_base_patch16_224.fb_in1k --keep_dataset aircraft_pl --x_var_name model_name_extractor --y_var_name acc_std --y_label 'Accuracy Standard Deviation' --keep_extractor ${all_resnet[@]} --x_var_name model_name_extractor --type_plot bar --input_file results_all/acc/acc_extractor/summary_val_acc_level1_main.csv --output_file compare_extractors_std_rn --title 'StD performance of Resnet extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --summarized --keep_methods hideit3_base_patch16_224.fb_in1k --keep_dataset aircraft_pl --x_var_name model_name_extractor --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --keep_extractor ${all_resnet[@]} --x_var_name model_name_extractor --type_plot bar --input_file results_all/acc/acc_extractor/summary_val_acc_level1_main.csv --output_file compare_extractors_ada_rn --title 'ADA ratio of Resnet extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'
# python -u plot.py --keep_serials 39 32 --font_scale 1.75 --fig_size 8 6 --loc_legend 'lower right' --keep_dataset soylocal --x_var_name n_cluster_ratio --y_var_name val_acc_level1 --x_label 'Cluster Ratio (%)' --y_label 'Accuracy (%)' --hue_var_name serial --type_plot box --input_file data/hierarchical_soylocal.csv --output_file compare_soylocal --title 'Accuracy of backbones on Soylocal dataset'
# python -u plot.py --keep_serials 39 32 --font_scale 1.75 --fig_size 8 6 --summarized --keep_dataset soylocal --x_var_name n_cluster_ratio --y_var_name ada_ratio --x_label 'Cluster Ratio (%)' --y_label 'Coefficient of Variation (%)' --hue_var_name serial --type_plot box --input_file results_all/acc/acc_soylocal/summary_val_acc_level1_main.csv  --output_file compare_soylocal_ada --title 'Overall performance of different models on Soylocal dataset'
# python -u plot.py --keep_serials 32 23 40 --loc_legend 'lower right' --keep_dataset aircraft cub cars --aggregate_dataset --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name dataset_name --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_acc --title 'Overall performance of different models on 3 settings: Baseline, Real Hierarchy, Pseudo-Hierarchy'
# python -u plot.py --keep_serials 32 23 40 --keep_dataset aircraft cub cars --summarized --aggregate_dataset --x_var_name serial --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name dataset_name --type_plot box --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_ada --title 'CV of different models on 3 settings: Baseline, Real Hierarchy, Pseudo-Hierarchy'
# python -u plot.py --keep_serials 40 --keep_ratios 25 50 70 --keep_dataset aircraft cub cars --summarized --aggregate_dataset --x_var_name n_cluster_ratio --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name dataset_name --type_plot box --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_ratios_ada --title 'CV of different pseudo-hierarchy ratios on 3 datasets'
# python -u plot.py --keep_serials 40 --loc_legend 'lower right' --keep_ratios 25 50 70 --keep_dataset aircraft cub cars --aggregate_dataset --x_var_name n_cluster_ratio --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name dataset_name --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_ratios_acc --title 'Overall performance of different pseudo-hierarchy ratios on 3 datasets'

# python -u plot.py --keep_serials 32 23 40 --keep_ratios 0 50 --loc_legend 'lower right' --keep_dataset aircraft cub cars --aggregate_dataset --x_var_name dataset_name --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name serial --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_acc_alt --title 'Overall performance of different models on 3 settings: Baseline, Real Hierarchy, Pseudo-Hierarchy'
# python -u plot.py --keep_serials 32 23 40 --keep_ratios 0 50 --keep_dataset aircraft cub cars --summarized --aggregate_dataset --x_var_name dataset_name --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name serial --type_plot box --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_ada_alt --title 'CV of different models on 3 settings: Baseline, Real Hierarchy, Pseudo-Hierarchy'

# python -u plot.py --keep_serials 40 --keep_ratios 25 50 70 --keep_dataset aircraft cub cars --summarized --aggregate_dataset --x_var_name dataset_name --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name n_cluster_ratio --palette pastel --type_plot box --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_ratios_ada_alt --title 'CV of different pseudo-hierarchy ratios on 3 datasets'
# python -u plot.py --keep_serials 40 --loc_legend 'lower right' --keep_ratios 25 50 70 --keep_dataset aircraft cub cars --aggregate_dataset --x_var_name dataset_name --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name n_cluster_ratio --palette pastel --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_ratios_acc_alt --title 'Overall performance of different pseudo-hierarchy ratios on 3 datasets'

# python -u plot.py --keep_serials 70 --font_scale 1.5 --fig_size 10 6 --summarized --keep_extractor 'hideit3_base_patch16_224.fb_in1k' 'hideit3_large_patch16_224.fb_in1k' 'hideit3_huge_patch16_224.fb_in1k' --x_var_name model_name_extractor --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --type_plot bar --input_file results_all/acc/acc_model_size/summary_val_acc_level1_main.csv --output_file compare_model_size_ada_alt --title 'hideit3_base_patch16_224.fb_in1k sizes on Aircraft in Pseudo-Hierarchy'

# python -u plot.py --keep_serials 40 51 --keep_ratios 50 --fig_size 24 6 --x_rotation 20 --font_scale 1.75 --summarized --keep_methods hideit3_base_patch16_224.fb_in1k --keep_dataset aircraft_pl --x_var_name model_name_extractor --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --keep_extractor ${all_models[@]} --x_var_name model_name_extractor --type_plot bar --input_file results_all/acc/acc_extractor/summary_val_acc_level1_main.csv --output_file compare_extractors_ada_all --title 'CV of all extractors on Aircraft with hideit3_base_patch16_224.fb_in1k model'

# keep_ratios=('25' '50' '70')
# datasets=('aircraft' 'cars' 'cub')
# for dataset in ${datasets[@]}; do
#     for ratio in ${keep_ratios[@]}; do
#         python -u plot.py --keep_serials 32 23 40 --font_scale 1.75 --fig_size 13 8 --x_rotation 20 --keep_ratios 0 ${ratio} --loc_legend 'lower left' --keep_methods ${all_resnet[@]} --keep_dataset ${dataset} --aggregate_dataset --x_var_name method --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name serial --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_acc_${dataset}_${ratio}_rn --title "Accuracy vs ResNet Backbones for ${dataset}"
#         python -u plot.py --keep_serials 32 23 40 --font_scale 1.75 --fig_size 13 8 --x_rotation 20 --keep_ratios 0 ${ratio} --loc_legend 'lower left' --keep_methods ${all_vit[@]} --keep_dataset ${dataset} --aggregate_dataset --x_var_name method --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name serial --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_acc_${dataset}_${ratio}_vit --title "Accuracy vs ViT Backbones for ${dataset}"

#         # python -u plot.py --keep_serials 32 23 40 --fig_size 20 6 --keep_ratios 0 50 --keep_dataset ${dataset} --keep_methods ${all_models[@]} --summarized --aggregate_dataset --x_var_name method --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name serial --type_plot box --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_ada_${dataset} --title 'CV of different models on 3 settings: Baseline, Real Hierarchy, Pseudo-Hierarchy'


#         python -u plot.py --keep_serials 40 --font_scale 1.75 --fig_size 8 6 --palette pastel --keep_ratios 25 50 70 --keep_dataset ${dataset} --summarized --aggregate_dataset --x_var_name dataset_name --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name n_cluster_ratio --type_plot box --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_ratios_ada_${dataset} --title "${dataset} Cluster Ratio Comparison"
#         python -u plot.py --keep_serials 40 --font_scale 1.75 --fig_size 8 6 --palette pastel --loc_legend 'lower right' --keep_ratios 25 50 70 --keep_dataset ${dataset} --aggregate_dataset --x_var_name dataset_name --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name n_cluster_ratio --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_ratios_acc_${dataset} --title "${dataset} Cluster Ratio Comparison"
#     done
# done

# for ratio in ${keep_ratios[@]}; do
#     python -u plot.py --keep_serials 40 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --loc_legend 'lower right' --keep_ratios ${ratio} --keep_extractor ${all_resnet[@]} --keep_dataset aircraft cub cars --aggregate_dataset --x_var_name method --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name dataset_name --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_${ratio}_acc_rn --title "Overall performance of different pseudo-hierarchy with ${ratio}% ratios on 3 datasets"
#     python -u plot.py --keep_serials 40 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --keep_ratios ${ratio} --keep_dataset aircraft cub cars --keep_extractor ${all_resnet[@]} --summarized --aggregate_dataset --x_var_name method --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name dataset_name --type_plot bar --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_${ratio}_ada_rn --title "CV of different pseudo-hierarchy with ${ratio}% ratios on 3 datasets"
#     python -u plot.py --keep_serials 40 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --loc_legend 'lower right' --keep_ratios ${ratio} --keep_extractor ${all_vit[@]} --keep_dataset aircraft cub cars --aggregate_dataset --x_var_name method --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --hue_var_name dataset_name --type_plot box --input_file data/hierarchical_pseudo_2.csv --output_file compare_main_plot_${ratio}_acc_vit --title "Overall performance of different pseudo-hierarchy with ${ratio}% ratios on 3 datasets"
#     python -u plot.py --keep_serials 40 --fig_size 10 6 --x_rotation 20 --font_scale 0.75 --keep_ratios ${ratio} --keep_dataset aircraft cub cars --keep_extractor ${all_vit[@]} --summarized --aggregate_dataset --x_var_name method --y_var_name ada_ratio --y_label 'Coefficient of Variation (%)' --hue_var_name dataset_name --type_plot bar --input_file results_all/acc/acc_pseudo_main/summary_val_acc_level1_main.csv --output_file compare_main_plot_${ratio}_ada_vit --title "CV of different pseudo-hierarchy with ${ratio}% ratios on 3 datasets"
# done

# for ratio in ${keep_ratios[@]}; do
#     python -u make_table.py --fig_size 6 6 --input_file pseudo_results/main_results/summary_pseudo_all.csv --keep_methods ${all_resnet[@]} --output_file results_all/table/main_results_air_rn_${ratio}.png --keep_ratios 0 ${ratio} --keep_serials 32 40 --keep_dataset aircraft --aggregate_dataset --columns serial dataset_name method n_cluster_ratio acc_mean rel_dif_acc_mean ada_ratio rel_dif_ada
#     python -u make_table.py --fig_size 6 6 --input_file pseudo_results/main_results/summary_pseudo_all.csv --keep_methods ${all_resnet[@]} --output_file results_all/table/main_results_cars_rn_${ratio}.png --keep_ratios 0 ${ratio} --keep_serials 32 40 --keep_dataset cars --aggregate_dataset --columns serial dataset_name method n_cluster_ratio acc_mean rel_dif_acc_mean ada_ratio rel_dif_ada
#     python -u make_table.py --fig_size 6 6 --input_file pseudo_results/main_results/summary_pseudo_all.csv --keep_methods ${all_resnet[@]} --output_file results_all/table/main_results_cub_rn_${ratio}.png --keep_ratios 0 ${ratio} --keep_serials 32 40 --keep_dataset cub --aggregate_dataset --columns serial dataset_name method n_cluster_ratio acc_mean rel_dif_acc_mean ada_ratio rel_dif_ada

#     python -u make_table.py --fig_size 6 6 --input_file pseudo_results/main_results/summary_pseudo_all.csv --keep_methods ${all_vit[@]} --output_file results_all/table/main_results_air_vit_${ratio}.png --keep_ratios 0 ${ratio} --keep_serials 32 40 --keep_dataset aircraft --aggregate_dataset --columns serial dataset_name method n_cluster_ratio acc_mean rel_dif_acc_mean ada_ratio rel_dif_ada
#     python -u make_table.py --fig_size 6 6 --input_file pseudo_results/main_results/summary_pseudo_all.csv --keep_methods ${all_vit[@]} --output_file results_all/table/main_results_cars_vit_${ratio}.png --keep_ratios 0 ${ratio} --keep_serials 32 40 --keep_dataset cars --aggregate_dataset --columns serial dataset_name method n_cluster_ratio acc_mean rel_dif_acc_mean ada_ratio rel_dif_ada
#     python -u make_table.py --fig_size 6 6 --input_file pseudo_results/main_results/summary_pseudo_all.csv --keep_methods ${all_vit[@]} --output_file results_all/table/main_results_cub_vit_${ratio}.png --keep_ratios 0 ${ratio} --keep_serials 32 40 --keep_dataset cub --aggregate_dataset --columns serial dataset_name method n_cluster_ratio acc_mean rel_dif_acc_mean ada_ratio rel_dif_ada
# done

# Heatmaps for Soylocal
# python -u plot.py --keep_serials 39 32 --font_scale 1.5 --fig_size 8 6 --keep_dataset soylocal --x_var_name n_cluster_ratio  --y_var_name lr --x_label 'Cluster Ratio (%)' --y_label 'Learning Rates' --hue_var_name val_acc_level1 --input_file data/hierarchical_soylocal.csv --output_file heatmap_soylocal --title 'Heatmap of Soylocal dataset' --type_plot heatmap
# python -u plot.py --keep_serials 39 32 --font_scale 1.5 --fig_size 8 6 --keep_dataset soylocal --x_var_name lr  --y_var_name batch_size --x_label 'Learning Rates' --y_label 'Batch Size' --hue_var_name val_acc_level1 --input_file data/hierarchical_soylocal.csv --output_file heatmap_soylocal_1d --title 'Heatmap of Soylocal dataset' --type_plot heatmap


# Soylocal stuff
python download_save_wandb_data.py --serials 72 73 --output_file soylocal_bs.csv
python summarize_acc.py --input_file data/soylocal_epochs.csv --main_serials 73 --results_dir results_all/soylocal_acc/acc_bs
python organize_pseudo.py --input_csv results_all/soylocal_acc/acc_epochs/summary_val_acc_level1_main.csv --main_serials 72 73 --output_dir soylocal_results/batch_sizes

python download_save_wandb_data.py --serials 74 75 --output_file soylocal_epochs.csv
python summarize_acc.py --input_file data/soylocal_epochs.csv --main_serials 74 75 --results_dir results_all/soylocal_acc/acc_epochs
python organize_pseudo.py --input_csv results_all/soylocal_acc/acc_epochs/summary_val_acc_level1_main.csv --main_serials 74 75 --output_dir soylocal_results/epochs

python download_save_wandb_data.py --serials 76 77 --output_file soylocal_is.csv
python summarize_acc.py --input_file data/soylocal_is.csv --main_serials 76 77 --results_dir results_all/soylocal_acc/acc_is
python organize_pseudo.py --input_csv results_all/soylocal_acc/acc_is/summary_val_acc_level1_main.csv --main_serials 76 77 --output_dir soylocal_results/image_size

python download_save_wandb_data.py --serials 78 79 --output_file soylocal_augs.csv
python summarize_acc.py --input_file data/soylocal_augs.csv --main_serials 78 79 --results_dir results_all/soylocal_acc/acc_augs
python organize_pseudo.py --input_csv results_all/soylocal_acc/acc_augs/summary_val_acc_level1_main.csv --main_serials 78 79 --output_dir soylocal_results/augs

python -u plot.py --keep_serials 78 79 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/soylocal_augs.csv --output_file soylocal_compare_augs --title 'Comparison of 12 augmentations of Soylocal with hideit_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
python -u plot.py --keep_serials 76 77 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/soylocal_is.csv --output_file soylocal_compare_is --title 'Comparison of 10 image sizes (is) of Soylocal with hideit_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
python -u plot.py --keep_serials 74 75 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/soylocal_epochs.csv --output_file soylocal_compare_epochs --title 'Comparison of 10 epochs of Soylocal with hideit_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
python -u plot.py --keep_serials 72 73 --x_var_name serial --y_var_name val_acc_level1 --y_label 'Accuracy (%)' --type_plot box --input_file data/soylocal_bs.csv --output_file soylocal_compare_bs --title 'Comparison of 10 batch_sizes of Soylocal with hideit_base_patch16_224.fb_in1k model in Baseline vs Pseudo-Hierarchy settings'
